if(NOT TARGET Python3::Python AND DEFINED ROS2_OHOS_TARGET_PYTHON_LIBRARY AND
    DEFINED ROS2_OHOS_TARGET_PYTHON_INCLUDE_DIR AND
    EXISTS "${ROS2_OHOS_TARGET_PYTHON_LIBRARY}" AND
    IS_DIRECTORY "${ROS2_OHOS_TARGET_PYTHON_INCLUDE_DIR}")
  add_library(Python3::Python SHARED IMPORTED GLOBAL)
  set_target_properties(Python3::Python PROPERTIES
    IMPORTED_LOCATION "${ROS2_OHOS_TARGET_PYTHON_LIBRARY}"
    INTERFACE_INCLUDE_DIRECTORIES "${ROS2_OHOS_TARGET_PYTHON_INCLUDE_DIR}")
endif()

if(NOT TARGET Python3::NumPy AND DEFINED ROS2_OHOS_TARGET_NUMPY_INCLUDE_DIR AND
    IS_DIRECTORY "${ROS2_OHOS_TARGET_NUMPY_INCLUDE_DIR}")
  add_library(Python3::NumPy INTERFACE IMPORTED GLOBAL)
  set_target_properties(Python3::NumPy PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES "${ROS2_OHOS_TARGET_NUMPY_INCLUDE_DIR}")
endif()
