<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>rmw_mdds_cpp</name>
  <version>0.1.0</version>
  <description>ROS middleware interface implementation backed by MDDS.</description>

  <maintainer email="kaihong@example.com">Kaihong</maintainer>
  <license>Apache License 2.0</license>

  <buildtool_depend>ament_cmake_ros</buildtool_depend>

  <build_depend>rmw</build_depend>
  <build_depend>rmw_dds_common</build_depend>
  <build_depend>fastcdr</build_depend>
  <build_depend>openssl</build_depend>
  <build_depend>rosidl_runtime_c</build_depend>
  <build_depend>rosidl_runtime_cpp</build_depend>
  <build_depend>rosidl_dynamic_typesupport</build_depend>
  <build_depend>rosidl_typesupport_c</build_depend>
  <build_depend>rosidl_typesupport_cpp</build_depend>
  <build_depend>rosidl_typesupport_fastrtps_c</build_depend>
  <build_depend>rosidl_typesupport_fastrtps_cpp</build_depend>
  <build_depend>rosidl_typesupport_introspection_c</build_depend>
  <build_depend>rosidl_typesupport_introspection_cpp</build_depend>

  <exec_depend>rmw</exec_depend>
  <exec_depend>rmw_dds_common</exec_depend>
  <exec_depend>fastcdr</exec_depend>
  <exec_depend>openssl</exec_depend>
  <exec_depend>rosidl_runtime_c</exec_depend>
  <exec_depend>rosidl_runtime_cpp</exec_depend>
  <exec_depend>rosidl_dynamic_typesupport</exec_depend>
  <exec_depend>rosidl_dynamic_typesupport_fastrtps</exec_depend>
  <exec_depend>rosidl_typesupport_c</exec_depend>
  <exec_depend>rosidl_typesupport_cpp</exec_depend>
  <exec_depend>rosidl_typesupport_fastrtps_c</exec_depend>
  <exec_depend>rosidl_typesupport_fastrtps_cpp</exec_depend>
  <exec_depend>rosidl_typesupport_introspection_c</exec_depend>
  <exec_depend>rosidl_typesupport_introspection_cpp</exec_depend>

  <test_depend>ament_cmake_gtest</test_depend>
  <test_depend>openssl</test_depend>
  <test_depend>builtin_interfaces</test_depend>
  <test_depend>example_interfaces</test_depend>
  <test_depend>geometry_msgs</test_depend>
  <test_depend>service_msgs</test_depend>
  <test_depend>std_msgs</test_depend>
  <test_depend>std_srvs</test_depend>
  <test_depend>test_msgs</test_depend>
  <test_depend>type_description_interfaces</test_depend>

  <member_of_group>rmw_implementation_packages</member_of_group>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
