#!/usr/bin/env python3

import argparse
import importlib.util
from pathlib import Path


COMMON_HEADER = """// generated by ohos/tools/generate_logging_macros.py

#ifndef RCUTILS__LOGGING_MACROS_H_
#define RCUTILS__LOGGING_MACROS_H_

#include "rcutils/logging.h"

#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>

#ifdef __cplusplus
  #define RCUTILS_CAST_DURATION(x) (static_cast<rcutils_duration_value_t>(x))
#else
  #define RCUTILS_CAST_DURATION(x) ((rcutils_duration_value_t)x)
#endif

#ifdef __cplusplus
extern "C"
{
#endif

#define RCUTILS_LOG_MIN_SEVERITY_DEBUG 0
#define RCUTILS_LOG_MIN_SEVERITY_INFO 1
#define RCUTILS_LOG_MIN_SEVERITY_WARN 2
#define RCUTILS_LOG_MIN_SEVERITY_ERROR 3
#define RCUTILS_LOG_MIN_SEVERITY_FATAL 4
#define RCUTILS_LOG_MIN_SEVERITY_NONE 5

#ifndef RCUTILS_LOG_MIN_SEVERITY
#define RCUTILS_LOG_MIN_SEVERITY RCUTILS_LOG_MIN_SEVERITY_DEBUG
#endif

#define RCUTILS_LOG_COND_NAMED(severity, condition_before, condition_after, name, ...) \\
  do { \\
    RCUTILS_LOGGING_AUTOINIT; \\
    static rcutils_log_location_t __rcutils_logging_location = {__func__, __FILE__, __LINE__}; \\
    if (rcutils_logging_logger_is_enabled_for(name, severity)) { \\
      condition_before \\
      rcutils_log_internal(&__rcutils_logging_location, severity, name, __VA_ARGS__); \\
      condition_after \\
    } \\
  } while (0)

#define RCUTILS_LOG_CONDITION_EMPTY

#define RCUTILS_LOG_CONDITION_ONCE_BEFORE \\
  { \\
    static int __rcutils_logging_once = 0; \\
    if (RCUTILS_UNLIKELY(0 == __rcutils_logging_once)) { \\
      __rcutils_logging_once = 1;
#define RCUTILS_LOG_CONDITION_ONCE_AFTER } \\
  }

#define RCUTILS_LOG_CONDITION_EXPRESSION_BEFORE(expression) \\
  if (expression) {
#define RCUTILS_LOG_CONDITION_EXPRESSION_AFTER }

typedef bool (* RclLogFilter)(void);

#define RCUTILS_LOG_CONDITION_FUNCTION_BEFORE(function) \\
  if ((*function)()) {
#define RCUTILS_LOG_CONDITION_FUNCTION_AFTER }

#define RCUTILS_LOG_CONDITION_SKIPFIRST_BEFORE \\
  { \\
    static bool __rcutils_logging_first = true; \\
    if (RCUTILS_UNLIKELY(true == __rcutils_logging_first)) { \\
      __rcutils_logging_first = false; \\
    } else {
#define RCUTILS_LOG_CONDITION_SKIPFIRST_AFTER } \\
  }

#define RCUTILS_LOG_CONDITION_THROTTLE_BEFORE(get_time_point_value, duration) { \\
  static rcutils_duration_value_t __rcutils_logging_duration = RCUTILS_MS_TO_NS(RCUTILS_CAST_DURATION(duration)); \\
  static rcutils_time_point_value_t __rcutils_logging_last_logged = 0; \\
  rcutils_time_point_value_t __rcutils_logging_now = 0; \\
  bool __rcutils_logging_condition = true; \\
  if (get_time_point_value(&__rcutils_logging_now) != RCUTILS_RET_OK) { \\
    rcutils_log( \\
      &__rcutils_logging_location, RCUTILS_LOG_SEVERITY_ERROR, "", \\
      "%s() at %s:%d getting current steady time failed\\n", \\
      __func__, __FILE__, __LINE__); \\
  } else { \\
    __rcutils_logging_condition = __rcutils_logging_now >= __rcutils_logging_last_logged + __rcutils_logging_duration; \\
  } \\
  if (RCUTILS_LIKELY(__rcutils_logging_condition)) { \\
    __rcutils_logging_last_logged = __rcutils_logging_now;
#define RCUTILS_LOG_CONDITION_THROTTLE_AFTER } \\
  }
"""


COMMON_FOOTER = """
#ifdef __cplusplus
}
#endif

#endif  // RCUTILS__LOGGING_MACROS_H_
"""


def load_logging_module(logging_py: Path):
    spec = importlib.util.spec_from_file_location("ros2_rcutils_logging_meta", logging_py)
    module = importlib.util.module_from_spec(spec)
    if spec.loader is None:
        raise RuntimeError(f"Unable to load {logging_py}")
    spec.loader.exec_module(module)
    return module


def macro_signature(parameters):
    names = list(parameters.keys())
    if not names:
      return "..."
    return ", ".join(names + ["..."])


def emit_active_macro(severity, suffix, signature, arguments):
    return [
        f"#define RCUTILS_LOG_{severity}{suffix}({signature}) \\",
        "  RCUTILS_LOG_COND_NAMED( \\",
        f"    RCUTILS_LOG_SEVERITY_{severity}, \\",
        f"    {arguments[0]}, \\",
        f"    {arguments[1]}, \\",
        f"    {arguments[2]}, \\",
        "    __VA_ARGS__)",
    ]


def build_header(logging_py: Path):
    module = load_logging_module(logging_py)
    lines = [COMMON_HEADER.rstrip(), ""]

    for severity in module.severities:
        lines.append(f"#if (RCUTILS_LOG_MIN_SEVERITY > RCUTILS_LOG_MIN_SEVERITY_{severity})")
        for feature_combination in module.feature_combinations:
            suffix = module.get_suffix_from_features(feature_combination)
            signature = macro_signature(module.get_macro_parameters(feature_combination))
            lines.append(f"#define RCUTILS_LOG_{severity}{suffix}({signature})")
        lines.append("#else")
        for feature_combination in module.feature_combinations:
            suffix = module.get_suffix_from_features(feature_combination)
            signature = macro_signature(module.get_macro_parameters(feature_combination))
            arguments = module.get_macro_arguments(feature_combination)
            lines.extend(emit_active_macro(severity, suffix, signature, arguments))
        lines.append("#endif")
        lines.append("")

    lines.append(COMMON_FOOTER.strip())
    lines.append("")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Generate rcutils/logging_macros.h without empy.")
    parser.add_argument("--logging-py", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()

    output = args.output
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(build_header(args.logging_py), encoding="utf-8")


if __name__ == "__main__":
    main()
