#!/usr/bin/env python3
"""Create the immutable import manifest used by an OHOS release checkout."""

import argparse
import os
import subprocess
import tempfile
from pathlib import Path

import yaml


ROOT = Path(__file__).resolve().parents[1]


def git(repo: Path, *args: str) -> str:
    result = subprocess.run(
        ["git", "-C", str(repo), *args],
        check=True,
        capture_output=True,
        text=True,
    )
    return result.stdout.strip()


def read_digest(path: Path, label: str) -> str:
    value = path.read_text(encoding="ascii").strip()
    if len(value) != 40 or any(ch not in "0123456789abcdef" for ch in value):
        raise ValueError(f"invalid {label}: {path}")
    return value


def require_fetchable_revision(relative: str, repo: Path, revision: str) -> None:
    refs = git(
        repo,
        "for-each-ref",
        "--format=%(refname)",
        "--contains",
        revision,
        "refs/remotes/origin",
        "refs/tags",
    ).splitlines()
    if not any(
        ref.startswith("refs/remotes/origin/") or ref.startswith("refs/tags/")
        for ref in refs
    ):
        raise ValueError(
            f"{relative}: revision {revision} is not contained in an origin ref/tag"
        )


def pinned_revision(relative: str, repo: Path) -> str:
    key = relative.replace("/", "__")
    series = ROOT / "patches" / f"{key}.patch"
    if series.exists():
        revision = read_digest(ROOT / "patches" / f"{key}.base", "series base")
    else:
        revision = git(repo, "rev-parse", "HEAD")
    git(repo, "cat-file", "-e", f"{revision}^{{commit}}")
    # A lock SHA is useful only when a fresh clone can obtain it. This local
    # containment check is followed by an actual empty-directory import in
    # release acceptance, which also catches stale remote-tracking refs.
    try:
        require_fetchable_revision(relative, repo, revision)
    except ValueError as exc:
        if not series.exists():
            raise ValueError(
                f"{relative}: HEAD {revision} is unpublished and has no fallback patch"
            ) from exc
        raise
    return revision


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", default="ros2.repos")
    parser.add_argument("--output", default="ros2.ohos.lock.repos")
    args = parser.parse_args()
    source = ROOT / args.input
    output = ROOT / args.output
    data = yaml.safe_load(source.read_text(encoding="utf-8"))
    repositories = data.get("repositories") if isinstance(data, dict) else None
    if not isinstance(repositories, dict) or not repositories:
        raise ValueError("manifest has no repositories mapping")

    rendered = [
        "# Generated by scripts/freeze_ros2_repos.py; do not hand-edit.",
        "# Import this file, then run scripts/apply_patches.sh.",
        "repositories:",
    ]
    for relative, spec in repositories.items():
        if not isinstance(spec, dict) or set(spec) != {"type", "url", "version"}:
            raise ValueError(f"unsupported manifest entry shape: {relative}")
        repo = ROOT / "src" / relative
        if not (repo / ".git").exists():
            raise ValueError(f"repository is not checked out: {relative}")
        revision = pinned_revision(relative, repo)
        rendered.extend(
            [
                f"  {relative}:",
                f"    type: {spec['type']}",
                f"    url: {spec['url']}",
                f"    version: {revision}",
            ]
        )
    payload = "\n".join(rendered) + "\n"
    output.parent.mkdir(parents=True, exist_ok=True)
    fd, temporary = tempfile.mkstemp(prefix=f".{output.name}.", dir=output.parent)
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as stream:
            stream.write(payload)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary, output)
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)
    print(f"wrote {output} with {len(repositories)} immutable revisions")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
