# Bind transitive ament vendor downloads to immutable public source objects.
# Non-OHOS builds retain upstream behavior.
include_guard(GLOBAL)

function(ohos_resolve_vendor_source vcs_type vcs_url requested_version out_version out_hash)
  set(resolved "${requested_version}")
  set(archive_hash "")
  if(vcs_type STREQUAL "path")
    # Local fixtures are already covered by the parent repository tree receipt.
  elseif(vcs_type STREQUAL "git" AND requested_version MATCHES "^[0-9a-f]+$")
    string(LENGTH "${requested_version}" revision_length)
    if(NOT revision_length EQUAL 40)
      message(FATAL_ERROR "OHOS vendor revision is not a full commit: ${vcs_url}")
    endif()
  else()
    file(READ "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/ohos-vendor-sources.lock.json" lock)
    string(JSON count LENGTH "${lock}" sources)
    math(EXPR last "${count} - 1")
    set(found FALSE)
    foreach(index RANGE 0 ${last})
      string(JSON entry_type GET "${lock}" sources ${index} type)
      string(JSON entry_url GET "${lock}" sources ${index} url)
      string(JSON entry_version GET "${lock}" sources ${index} requested_version)
      if(vcs_type STREQUAL entry_type AND vcs_url STREQUAL entry_url
          AND requested_version STREQUAL entry_version)
        if(vcs_type STREQUAL "git")
          string(JSON resolved GET "${lock}" sources ${index} commit)
          string(LENGTH "${resolved}" digest_length)
          if(NOT digest_length EQUAL 40 OR NOT resolved MATCHES "^[0-9a-f]+$")
            message(FATAL_ERROR "Invalid OHOS vendor commit: ${vcs_url}")
          endif()
        elseif(vcs_type STREQUAL "zip" OR vcs_type STREQUAL "tar")
          string(JSON digest GET "${lock}" sources ${index} sha256)
          string(LENGTH "${digest}" digest_length)
          if(NOT digest_length EQUAL 64 OR NOT digest MATCHES "^[0-9a-f]+$")
            message(FATAL_ERROR "Invalid OHOS vendor archive hash: ${vcs_url}")
          endif()
          set(archive_hash "SHA256=${digest}")
        else()
          message(FATAL_ERROR "Unsupported OHOS vendor source type: ${vcs_type}")
        endif()
        set(found TRUE)
        break()
      endif()
    endforeach()
    if(NOT found)
      message(FATAL_ERROR "Unpinned OHOS vendor source: ${vcs_type} ${vcs_url} ${requested_version}")
    endif()
  endif()
  set(${out_version} "${resolved}" PARENT_SCOPE)
  set(${out_hash} "${archive_hash}" PARENT_SCOPE)
endfunction()
